# Generated by Django 5.2.12 on 2026-04-01 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#6B7280", max_length=7)),
                ("order", models.IntegerField(default=0)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project statuses",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="accounts.team",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="projects.projectstatus",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_url", models.URLField(blank=True)),
                ("appstore_url", models.URLField(blank=True)),
                ("figma_url", models.URLField(blank=True)),
                ("domain_name", models.CharField(blank=True, max_length=253)),
                ("domain_registrar", models.CharField(blank=True, max_length=200)),
                ("domain_expires", models.DateField(blank=True, null=True)),
                (
                    "budget_required",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("budget_currency", models.CharField(default="RUB", max_length=3)),
                ("ad_cabinet_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_card",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechnicalCardCustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("value", models.TextField()),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("url", "Ссылка"),
                            ("date", "Дата"),
                            ("number", "Число"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="projects.technicalcard",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
